name: Deploy to GitHub Pages (with LFS)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with Git LFS)
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Ensure LFS objects present (debug)
        run: |
          git lfs install --local
          git lfs fetch --all
          git lfs checkout
          echo "[CI] LFS files:"
          git lfs ls-files -l || true

      # If your site files live in /frontend (canonical), keep this.
      # If index.html is at repo root instead, change ./frontend/ to ./ below.
      - name: Prepare static site
        run: |
          mkdir -p dist
          rsync -av --delete --exclude '.git*' --exclude '.github' ./frontend/ ./dist/
          # ensure Jekyll doesn't strip assets
          touch dist/.nojekyll

      - name: List trees (debug)
        run: |
          echo "[CI] FRONTEND:"
          ls -la ./frontend
          echo "[CI] FRONTEND/models:"
          ls -la ./frontend/models || true
          ls -la ./frontend/models/Player || true
          echo "[CI] DIST ROOT:"
          ls -la ./dist
          echo "[CI] DIST/models:"
          ls -la ./dist/models || true
          ls -la ./dist/models/Player || true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
